# -*- coding: utf-8 -*-
"""matplotlib_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pg21-W2wDZrSRcD7IFSWxEcJ_6VKLCoK
"""

# !pip install matplotlib

import pandas as pd
import matplotlib.pyplot as plt

sales=pd.DataFrame({
    "Month":["Jan","Feb","Mar","Apr","May","Jun"],
    "Sales":[120000,135000,150000,170000,165000,190000]
})
sales

plt.figure(figsize=(4,3))
plt.plot(sales["Month"],sales["Sales"],marker='o',color='green',linewidth=2)
plt.title("Graph for Sales vs months")
plt.xlabel("Months")
plt.ylabel("Sales")
plt.show()

employee=pd.DataFrame({
    "Experience":[1,2,3,4,5,6,7,8,9,10],
    "Salary":[25000,30000,35000,42000,50000,58000,68000,76000,85000,95000]
})
employee

# scatter plot

plt.figure(figsize=(8,5))
plt.scatter(employee['Experience'],employee['Salary'],s=100,color='green')


plt.title("Experience vs Salary")
plt.xlabel("Experience")
plt.ylabel("Salary")
plt.grid(True)

plt.show()

products=pd.DataFrame({
    "Product":["Laptop","Phone","tablet","watch","headphone"],
    "Sales":[550,720,320,410,290]
})
products

plt.figure(figsize=(5,3))
plt.bar(products["Product"],products["Sales"],color="green")
plt.title("Sales by product")
plt.xlabel("Products")
plt.ylabel("units Sold")

plt.show()

plt.figure(figsize=(5,3))
plt.barh(products["Product"],products["Sales"],color="orange")  # use bar + h= barh for horizontal chart and dont use this they give by default vertical chart
plt.title("Sales by product")
plt.xlabel("Products")
plt.ylabel("units Sold")

plt.show()

salary=pd.DataFrame({
    "Salary":[25000,28000,30000,32000,35000,
              36000,40000,42000,45000,50000,
              52000,55000,60000,65000,70000
            ]
})
salary

plt.figure(figsize=(5,3))
plt.hist(salary["Salary"],bins=5,edgecolor="black")
plt.title("Salary Distribution")
plt.xlabel("Salary")
plt.ylabel("Frequency")
plt.show()

# this is same work as a above work but this is donr by using seaborn.
import seaborn as sns
df=sns.load_dataset('tips')
df

plt.figure(figsize=(5,3))
plt.hist(df["total_bill"],bins=5,edgecolor="black")
plt.show()