# -*- coding: utf-8 -*-
"""Matplotlib_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kYDDKaFuGbGqe6frDmilFZb3dIvxcRAt
"""

import pandas as pd
import matplotlib.pyplot as plt

market = pd.DataFrame({
    "Company":["Apple","Samsung","Xiamoi","Oneplus"],
    "Share":[40,30,20,10]
})

plt.pie(market["Share"],labels=market["Company"],
        autopct="%1.2f%%",startangle=90)
plt.show()

traffic=pd.DataFrame({
    "Month":["jan","feb","mar","apr","may","jun"],
    "Desktop":[1200,1400,1600,1700,1800,2000],
    "Mobile":[1800,2100,2500,2700,3000,3400]
})

plt.plot(traffic["Month"],traffic["Desktop"],marker="o",label="Desktop")

plt.plot(traffic["Month"],traffic["Mobile"],marker="s",label="Mobile")

plt.legend()

plt.title("Website visitors")
plt.xlabel("Month")
plt.ylabel("Visitors")

plt.grid(True)
plt.show()

import pandas as pd

sales = pd.DataFrame({
"Month": ["Jan", "Feb", "Mar", "Apr", "May", "Jun"],
"sales": [120, 150, 130, 180, 160, 200]
})

employee = pd.DataFrame({
"Experience": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
"Salary": [30000, 35000, 40000, 45000, 50000, 55000, 60000, 65000, 70000, 75000]
})

salary = pd.DataFrame({
"Salary": [30000, 32000, 35000, 38000, 40000, 42000, 45000, 48000, 50000, 52000, 55000, 58000, 60000, 62000, 65000]
})

products = pd.DataFrame({
"Product": ["A", "B", "C", "D", "E"],
"Sales": [100, 150, 80, 120, 90]
})

#subplots
fig, ax = plt.subplots(2,2,figsize=(10,8))

ax[0,0].plot(sales["Month"],sales["sales"])
ax[0,0].set_title("Sales")

ax[0,1].scatter(employee["Experience"],employee["Salary"])
ax[0,1].set_title("Experience")

ax[1,0].hist(salary["Salary"])
ax[1,0].set_title("Salary Distribution")

ax[1,1].bar(products["Product"],products["Sales"])
ax[1,1].set_title("Sales")

plt.tight_layout()
plt.show()

# pivot table
data = {
    "region":["east","west","east","west","east","west"],
    "product":["apple","apple","banana","banana","apple","banana"],
    "sales":[100,150,200,250,120,300],
    "profit":[30,45,60,70,35,90]
}
df=pd.DataFrame(data)
df

# pivot table
df.pivot_table(index="product",values="sales",aggfunc="mean")