# -*- coding: utf-8 -*-
"""Numpy_Introduction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XdDJTfVJoPXzgHA8kEoEz_dAKRXr3YKw
"""

!pip install numpy # this command  is use for download numpy

import numpy as np

#create an array using numpy
arr=np.array([1,2,3,4])
arr + 1

arr[0]

arr[1:]

matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix + 1

np.zeros((2,3))

np.ones((3,4))

np.eye(4)

matrix.ndim

arr = np.arange(1,19)
arr.reshape(3,6)

arr.reshape(6,3)

np.random.seed(22)
np.random.rand(10)

np.random.seed(22)
np.random.randint(1,100,10)