# -*- coding: utf-8 -*-
"""Numpy_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GGCo2VD_uf7IezLodZ1vTNpaM3a3PnWO
"""

import numpy as np

arr = np.array([
              [1,2,3],
               [4,5,6],
               [7,8,9]
               ])

arr[0:2,0:2]

import numpy as np

arr = np.array([
              [1,2,3],
               [4,5,6],
               [7,8,9]
               ])


arr[0][1]

arr.flatten()

arr.ravel()

arr = np.array([
              [1,2,3],
               [4,5,6],
               [7,8,9]
               ])

np.sum(arr,axis=1)

np.sum(arr,axis=0)

# implement all the aggregate function with axis =1 & axis=0