# -*- coding: utf-8 -*-
"""Pandas_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eB1Lb3RrVP4vZMpORfiAL3j2lz2FdWSD
"""

!pip install pandas   # use this command for install pandas library

import pandas as pd

import pandas as pd
pd.DataFrame(
    [
        ['Aman',20],
        ['Naman',35],
        ['Vikas',50]
    ],
      columns=('Name', 'marks')
)

import pandas as pd

df=pd.read_csv('/content/CarPrice_Assignment.csv')
df