# -*- coding: utf-8 -*-
"""Pandas_Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uej7FYw6YUxhcpzoWEYS0oxU_7iGMyHZ
"""

import pandas as pd
df=pd.read_csv('/content/StudentsPerformance.csv')
df

# 3. Display the first 10 rows.
df.head(10)

# 4. Display the last 10 rows.
df.tail(10)

# 5. Find the number of rows and columns.
df.shape  # we find only rows then give [0] , and find columns then give [1]

# 6. Display all column names.
df.columns

# 7. Check the data types of every column.
df.dtypes

# 8. Display the dataset summary.
df.info()

# 9. Display descriptive statistics.
df.describe()

# 10. Check memory usage.
df.memory_usage()

# 11. Check whether the dataset contains missing values.
df.isnull()

# 12. Count missing values column-wise.
df.isnull().sum()

# 13. Check duplicate rows.
df.duplicated()

# 14. Remove duplicate rows.
df=df.drop_duplicates()
df

# 15. Count unique values in every column.
df.nunique()

# 16. Display unique genders.
df['gender'].unique()

# 17. Display unique parental education levels.
df['parental level of education'].unique()

# 18. Display unique lunch categories.
df['lunch'].unique()

# 19. Display unique test preparation categories.
df['test preparation course'].unique()

# 20. Display the frequency of each gender.
df['gender'].value_counts()

# Part 3: Selecting Data

# 21. Display only the math score column.
df['math score']

# 22. Display reading and writing scores.
df[['reading score','writing score']]

# 23. Display the first 20 rows.
df.head(20)

# 24. Display rows 30–50.
df.iloc[30:51]