# -*- coding: utf-8 -*-
"""Pandas_assignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-EbCOqD-AHpL7TgdNoJOMSiD4ayuGcit
"""

# 1. Load the Titanic dataset.
import pandas as pd
df=pd.read_csv("/content/Titanic-Dataset.csv")
df

# 2. Display the first 10 rows.
df.head(10)

# 3. Display the last 10 rows.
df.tail(10)

# 4. Find the number of rows and columns.
df.shape

# 5. Display the column names.
df.columns

# 6. Display the data types of all columns.
df.dtypes

# 7. Generate summary statistics of numerical columns.
df.describe(include="number")

# 8. Generate summary statistics of categorical columns.
df.describe(include="object")

# 9. Display random 15 records.
df.sample(15)

# 10. Identify numerical and categorical columns.
cat_col=df.select_dtypes(include=[object])
num_col=df.select_dtypes(exclude=[object])
cat_col
num_col

# Part B: Data Selection & Filtering (10 Marks)

# 1. Display only the Name column.
df["Name"]

# 2. Display Name , Age , and Fare .
df[["Name","Age","Fare"]]

# 3. Display passengers whose age is greater than 40.
df[df["Age"]>40]

# 4. Display female passengers.
df[df["Sex"]=="female"]

# 5. Display passengers who survived.
df[df["Survived"]==1]

# 6. Display passengers who paid a fare greater than 100.
df[df["Fare"]>100]

# 7. Display passengers traveling in First Class.
df[df["Pclass"]==1]

# 8. Display passengers whose age is between 20 and 40.
df[(df["Age"]>=20) & (df["Age"]<=40)]

# 9. Display passengers who embarked from Southampton ( S ).
df[df["Embarked"]=="S"]

# 10. Display passengers who are younger than 18.
df[df["Age"]< 18]

# Part C: Data Cleaning (20 Marks)
# The company has noticed missing and inconsistent information in the dataset.

# 1. Find the missing values in each column.
df.isnull().sum()

# 2. Identify the column with the highest number of missing values.
df.isnull().sum().sort_values(ascending=False)

# 3. Display all rows where Age is missing.
df[df["Age"].isnull()]

# 4. Display all rows where Cabin is missing.
df[df["Cabin"].isnull()]

# 5. Remove rows where Age is missing
df=df.dropna(subset=["Age"])
df

# 6. Fill missing Age values using the median
df["Age"]=df["Age"].fillna(df["Age"].median())
df["Age"]

# 7. Fill missing Embarked values using the mode.