# -*- coding: utf-8 -*-
"""pandasNotebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bC6F9SO30mlj6sGvMIZB-VwpWyXPEnm1
"""

!pip install pandas

import pandas as pd

# Data type
#  Series

import numpy as np
arr = np.array([1,2,3,4]) + 1
arr[0]

# Series in Pandas
# Series is a one dimensional data in which the indices
# are also shown..
s = pd.Series([1,2,3,4])
s[0]

# A dataframe is a data type present in pandas in which
# the data is stored into the form of rows and columns
# Syntax -> pd.DataFrame(dictionary)
pd.DataFrame({
    'A':[1,2,3, 4],
    'B':[10, 20, 30, 40]
})

s = pd.Series([1.1, 2.1, 3, 4])
s[0]

s.size

s.dtype

s[0:2]

# Dataframe
# By using dictionary
# by using list
pd.DataFrame(
  [
      ['Aman', 20],
      ['naman', 35],
      ['vikash', 50]
  ],
  columns=['Name', 'Marks']
)

df = pd.read_csv('/content/sample_data/california_housing_train.csv')

df

df.head()

df.tail()

df.sample(5)

import pandas as pd

df = pd.read_csv('/content/CarPrice_Assignment.csv')

df.columns

df.info()

df.describe()

df['CarName']

df.columns

df[['doornumber', 'carbody', 'drivewheel']]

'four'

df[df['doornumber'] == 'two']

cat_cols = df.select_dtypes(include='object').columns
num_cols = df.select_dtypes(exclude='object').columns

df[num_cols]

df[cat_cols]

# Loc & Iloc
# Coditional selection of the entries
# How to handle the missing or null values..

import pandas as pd
df = pd.read_csv('/content/train.csv')

df.shape

df

df.columns

df.head()

df.info()

cat_cols = df.select_dtypes(include='object').columns
num_cols = df.select_dtypes(exclude='object').columns

num_cols

cat_cols

df[cat_cols]

df[num_cols]

df.iloc[0:3]

df.loc[0:3]

import numpy as np

data = pd.DataFrame({
    'Age':[20, 23, 24, np.nan],
    'Height':[np.nan, 180, 165, 177],
    'Name':['Maan', np.nan, 'Naman', 'Vikash']
}, index=['a', 'b', 'c', 'd'])

# data.loc['a':'c']
# new_data = data.loc['a':'b', 'Height':'Name']
# # To select a particular row from the dataframe on the
# # basis of the labels then we must have to use the loc
# # df.loc[row_slicing, column_slicing]
# new_data.to_csv('new_data.csv', index=False)
data

# Iloc
data.iloc[0:3, 0:2]
# Iloc is known as integer based indexing into which
# we basically select the particular row and column on the
# basis of integer based indexing. Into this the end index
# exclusive
# syntax -> df.iloc[row_slicing, column_slicing]

data.isna()

# How to handle the missing values of the data frame
# So, first of all we have to check whether the data is
# having any null value or not ?
data.isna().sum()

# There are two methods for null value handling
# Dropping the null values
# Impute the null values

data.dropna()
# if there is very less amount of the null present in the
# dataframe then we can use the dropna..but it could lead to
# the data loss

df[cat_cols].isna().sum()

df[num_cols].isna().sum()

# Imputing the numerical columns which are having the null values
# it can be imputed by two ways -> mean, median
# if the column is having any extreme value (outlier) then you must have
# to impute that with median
# if the columns is not having any outlier then we must have to fill that
# with mean..

df['LotFrontage'].isna().sum()

df['LotFrontage'].fillna(df['LotFrontage'].mean(), inplace=True)

df['LotFrontage'].isna().sum()

df['Alley'].isna().sum()

df.drop('Alley', axis=1, inplace=True)

df.shape

df['LotShape'].isna().sum()

df['BsmtCond'].isna().sum()

mode = df['BsmtCond'].mode()[0]

df['BsmtCond'].fillna(mode, inplace=True)

df['BsmtCond'].isna().sum()

df['BsmtCond'].value_counts()

cat_cols

# Handling Null Values

# Data
# Categorical -> null value -> mode imputation
# Numerical -> null value -> impute with median or mean

# Column 50 % > null values -> Drop particular
# 1% or 2% -> Drop using dropna.

import pandas as pd
df = pd.read_csv('/content/train.csv')

df['MSZoning'].unique()

df[df['LotArea'] > 10000]

df[df['MSZoning'] == 'RL']

df

for col in df.columns:
  print(col)

data = pd.DataFrame({
    'Col1':[20, 30, 35, 42, 31],
    'Col2':[35, 48, 45, 45, 41],
    'Full':['Aman Singh', 'naman Singh', 'shivam Sharma', 'Vishal Tawri', 'Yash Raj']
})

data['Full'].str.split(' ')

data['Name'].str.lower()

data.sort_values(by='Col2')

data.sort_values(by='Col1')

# Add a new col
data['Col3'] = 10

data['Col4'] = data['Col1'] + data['Col2']

# Drop column
data.drop('Col3', axis=1, inplace=True)

data

# Value sorting

data

data

data.drop_duplicates(inplace=True)

data.duplicated()