# -*- coding: utf-8 -*-
"""panda_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FVUbGUX_Gca9gnszux3SHAD61E4nnCgb
"""

import pandas as pd
data = pd.DataFrame({
    'dept':['IT','IT','Sales','IT','Sales'],
    'salary':[20000,22000,15000,20000,18000]
})
data.groupby("dept")['salary'].mean()

import pandas as pd
df1=pd.DataFrame({
    "emp_id":[101,102],
    "name":["Vinay","Aman"]
})

df2=pd.DataFrame({
    "emp_id":[103,104],
    "name":["Riya","Priya"]
})

vertical=pd.concat([df1,df2])
print(vertical)

employee=pd.DataFrame({
    "emp_id":[101,102,103],
    "Name":["vinay","aman","Riya"]
})

salary=pd.DataFrame({
    "salary":[50000,45000,60000],
    "Bonus":[5000,3000,7000]
})

horizontal=pd.concat(
    [employee,salary,],
    axis=1
)
print(horizontal)

employee=pd.DataFrame({
    "emp_id":[101,102,103,104],
    "Name":["vinay","aman","Riya","priya"]
})

salary=pd.DataFrame({
    "emp_id":[101,102,105],
    "salary":[50000,45000,60000],

})

inner=pd.merge(
    employee,
    salary,
    on="emp_id",
    how="left"
)
print(inner)

df = pd.DataFrame({
    "age": [15, 25, 65, None, 45, 12]
})

def age_category(age):
  if pd.isnull(age):
    return "unknown"
  elif age < 18:
    return "child"
  elif age < 60:
    return "adult"
  else:
    return "senior citizen"

df["age_category"]=df["age"].apply(age_category)
df