# -*- coding: utf-8 -*-
"""Seaborn_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bsv4NL9rsUB3OGa9XziCHQ2fFYLL10Gz
"""

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

df= sns.load_dataset("titanic")

df.info()

plt.figure(figsize=(5,3))

sns.histplot(
    data =df,
    x="age",
    bins=20,
    kde=True,
    color="skyblue"
)

plt.title("Age distribution")
plt.show()

plt.figure(figsize=(5,3))

sns.kdeplot(
    data=df,
    x="age",
    fill=True
)
plt.show()

plt.figure(figsize=(5,3))

sns.scatterplot(
    data=df,
    x="age",
    y="fare"
)
plt.show()

plt.figure(figsize=(5,3))

sns.scatterplot(
    data=df,
    x="age",
    y="fare",
    hue="sex"
)
plt.show()

avg_age=df.groupby("pclass")["age"].mean().reset_index()

sns.lineplot(
    data=avg_age,
    x="pclass",
    y="age",
    marker="o"
)
plt.show()

sns.violinplot(
    data=df,
    x="sex",
    y="fare"
)
plt.show()

sns.pairplot(
    df[
        [
            "age",
            "fare",
            "sibsp",
            "parch",
            "survived"
        ]
    ],
    hue="survived"
)
plt.show()

corr = df.select_dtypes("number").corr()
plt.figure(figsize=(8,6))

sns.heatmap(
    corr,
    annot=True,
    cmap="coolwarm"
)

plt.show()

