# -*- coding: utf-8 -*-
"""Vectorization_numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13HcepP6HCPeRqjbBJCzaey6fc1KA5DZt
"""

import numpy as np
matrix=np.arange(1,13).reshape(3,4)
matrix + 1

import numpy as np

# fancy indexing
arr= np.array([1,2,3,4,6,7,8,9,10])

arr[[2,5,7]]

arr[0:2]

import numpy as np

matrix = np.arange(1,13).reshape(3,4)
mat2=np.arange(1,5).reshape(1,4)
matrix + mat2

matrix  # break the above program into small code for learning and saw how it worked

mat2  # break the above program into small code for learning and saw how it worked