# -*- coding: utf-8 -*-
"""Vectorization_1numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13HcepP6HCPeRqjbBJCzaey6fc1KA5DZt
"""

#1
import numpy as np
matrix=np.arange(1,13).reshape(3,4)
matrix + 1

#2
import numpy as np

# fancy indexing
arr= np.array([1,2,3,4,6,7,8,9,10])

arr[[2,5,7]]

arr[0:2]

#3
import numpy as np

matrix = np.arange(1,13).reshape(3,4)
mat2=np.arange(1,5).reshape(1,4)
matrix + mat2

matrix  # break the above program into small code for learning and saw how it worked

mat2  # break the above program into small code for learning and saw how it worked

import numpy as np  # boolean indexing topic in numpy

arr = np.array([1,2,3,4,5])
arr > 2

arr [arr > 2]  # boolean indexing topic in numpy

arr[arr % 2 != 0]   # boolean indexing topic in numpy

import numpy as np  # boolean indexing topic in numpy

student = np.array([20,30,10,50,65,43])
print(student[student > 43])

new = np.where(student > 43,'pass','fail')
print(new)

arr = np.array([1,2,3,4,6,7,8,9,10])
arr[[2,5,7]]

mat1 = np.array([
    [1,2],
    [3,4]
])

mat2 = np.array([
    [5,6],
    [7,8]
])

np.concatenate([mat1,mat2],axis=0)  # axis = 0 is used for rows operation performed

np.concatenate([mat1,mat2],axis=1) # axis = 1 is used for coloumns operation performed